# This is a basic workflow to help you get started with Actions

name: Commit-Via-GH-API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    
      - name: Commit changes
        uses: grafana/github-api-commit-action@v0.1.0
        with:
          token: ${{ steps.get_installation_token.outputs.token }} # Token you want to authenticate with
          commit-message: "123-commit-message" # Commit message defaults to "Commit performed by grafana/github-api-commit-action"
          stage-all-files: false  # Whether to additionally stage any changed files in the checkout. Defaults to false
          # use-checkout-repo: false # Whether to use the repo from the checked out .git directory. Defaults to false, meaning it will use the action context repo.
