
# This is a basic workflow to help you get started with Actions
name: Deploy Sample App
env:
  RESOURCE_GROUP: 'brdev2rg'
  CLUSTER_NAME: 'brdev2aks'
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'sampleapp/**' 
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  actions: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: 
      group: default
    steps:
    - name: Install azure cli
      uses: pietrobolcato/install-azure-cli-action@v1.0.1
    - name: Install kubectl 
      uses: Azure/setup-kubectl@v4.0.0
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ env.RESOURCE_GROUP }}' 
        cluster-name: '${{ env.CLUSTER_NAME }}'
    - name: Install Runner
      run: |
          kubectl apply -f ./sampleapp/app-deployment.yaml 
