name: Load Test
on: [push]
jobs:
  Execute-Simple-K6:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Setup K6
      uses: grafana/setup-k6-action@v1.1.0      
    - name: Run k6 test
      uses: grafana/run-k6-action@v1.1.1
      with:       
          
          # Path to the k6 test files
          path: src/simple-test.js
          # If true, run tests in parallel
          parallel: true # optional          
          # If true, run tests locally instead and upload results to Grafana Cloud k6
          cloud-run-locally: true # optional, default is true
          # If true, comment the cloud test run URL on the pull request
          cloud-comment-on-pr: true # optional, default is true
          # If true, only check if the test scripts are valid and skip test execution
          only-verify-scripts: false # optional, default is false    
          
